modLoader="javafml"
loaderVersion="[41,)"
license="Apache License"
issueTrackerURL="https://www.github.com/MelanX/SkyblockBuilder/issues/"

[[mods]]
modId="skyblockbuilder"
version="${file.jarVersion}"
displayName="Skyblock Builder"
updateJSONURL="https://assets.melanx.de/updates/skyblock-builder.json"
displayURL="www.curseforge.com/members/melanx/"
authors="MelanX"
description='''
Let you create a custom skyblock island via config
'''

[[dependencies.skyblockbuilder]]
    modId = "forge"
    mandatory = true
    versionRange = "[41.0.35,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.skyblockbuilder]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19, 1.20)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.skyblockbuilder]]
    modId = "libx"
    mandatory = true
    versionRange = "[1.19-4.0.3,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.skyblockbuilder]]
    modId = "minemention"
    mandatory = false
    versionRange = "[1.19-2.0.0,)"
    ordering = "NONE"
    side = "BOTH"
