modLoader="javafml"
loaderVersion="[42,)"
license="Apache License"
issueTrackerURL="https://www.github.com/MelanX/SkyblockBuilder/issues/"

[[mods]]
modId="skyblockbuilder"
version="${file.jarVersion}"
displayName="Skyblock Builder"
updateJSONURL="https://assets.melanx.de/updates/skyblock-builder.json"
displayURL="www.curseforge.com/members/melanx/"
authors="MelanX"
description='''
Let you create a custom skyblock island via config
'''

[[dependencies.skyblockbuilder]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.1.2,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.skyblockbuilder]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2, 1.20)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.skyblockbuilder]]
    modId = "libx"
    mandatory = true
    versionRange = "[1.19.2-4.2.1,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.skyblockbuilder]]
    modId = "minemention"
    mandatory = false
    versionRange = "[1.19.1-2.1.0,)"
    ordering = "NONE"
    side = "BOTH"
