modLoader="javafml"
loaderVersion="[37,)"
license="Apache License"
issueTrackerURL="https://www.github.com/MelanX/SkyblockBuilder/issues/"

[[mods]]
modId="skyblockbuilder"
version="${file.jarVersion}"
displayName="Skyblock Builder"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/skyblockbuilder.json"
displayURL="www.curseforge.com/members/melanx/"
#logoFile="skyblockbuilder.png"
credits=""
authors="MelanX"
description='''
Let you create a custom skyblock island via config
'''

[[dependencies.skyblockbuilder]]
    modId = "forge"
    mandatory = true
    versionRange = "[37.0.53,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.skyblockbuilder]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.17.1,1.18)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.skyblockbuilder]]
    modId = "libx"
    mandatory = true
    versionRange = "[1.17.1-2.0.13,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.skyblockbuilder]]
    modId = "minemention"
    mandatory = false
    versionRange = "[1.17.1-1.0.1,)"
    ordering = "NONE"
    side = "BOTH"
