modLoader="javafml"
loaderVersion="[35,)"
license="Apache License"
issueTrackerURL="http://www.github.com/MelanX/CustomSkyblockWorldGenerator/issues/"

[[mods]]
modId="skyblockworldgenerator"
version="${file.jarVersion}"
displayName="Mod ID"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/skyblockworldgenerator.json"
displayURL="www.curseforge.com/members/melanx/"
#logoFile="skyblockworldgenerator.png"
credits=""
authors="MelanX"
description='''

'''

[[dependencies.skyblockworldgenerator]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.skyblockworldgenerator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4, 1.17)"
    ordering="NONE"
    side="BOTH"
