modLoader="javafml"
loaderVersion="[${fml},)"
license="Apache License"
issueTrackerURL="https://www.github.com/MelanX/SkyblockBuilder/issues/"

[[mods]]
modId="skyblockbuilder"
version="${version}"
displayName="Skyblock Builder"
updateJSONURL="https://assets.melanx.de/updates/skyblock-builder.json"
displayURL="www.curseforge.com/members/melanx/"
authors="MelanX"
description='''
Let you create a custom skyblock island via config
'''

[[dependencies.skyblockbuilder]]
    modId = "forge"
    mandatory = true
    versionRange="[${forge},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.skyblockbuilder]]
    modId = "minecraft"
    mandatory = true
    versionRange="[${minecraft},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.skyblockbuilder]]
    modId = "libx"
    mandatory = true
    versionRange="[1.20.1-5.0.5,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.skyblockbuilder]]
    modId = "minemention"
    mandatory = false
    versionRange = "[1.20.1-3.0.0,)"
    ordering = "NONE"
    side = "BOTH"
