modLoader="javafml"
loaderVersion="[35,)"
license="Apache License"
issueTrackerURL="http://www.github.com/MelanX/SkyblockBuilder/issues/"

[[mods]]
modId="skyblockbuilder"
version="${file.jarVersion}"
displayName="Skyblock Builder"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/skyblockbuilder.json"
displayURL="www.curseforge.com/members/melanx/"
#logoFile="skyblockbuilder.png"
credits=""
authors="MelanX"
description='''
Let you create a custom skyblock island via config
'''

[[dependencies.skyblockbuilder]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.skyblockbuilder]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4, 1.17)"
    ordering="NONE"
    side="BOTH"
