name: Bug Report (Dump Mode)
description: Report an issue with supported versions of Skyblock Builder
labels: [ bug ]
body:
  - type: dropdown
    id: mc-version
    attributes:
      label: Minecraft version
      options:
        - 1.20.1
    validations:
      required: true
  - type: textarea
    id: dump-file
    attributes:
      label: Dump File
      placeholder: Please only put the dump file in here.
  - type: textarea
    id: description
    attributes:
      label: Issue description
      placeholder: A description of the issue.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. First step
        2. Second step
        3. etc...
  - type: textarea
    id: additional-information
    attributes:
      label: Other information
      description: Any other relevant information that is related to this issue, such as modpacks, other mods and their versions.
